# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: insberr
          
          template: classic
          base: header, activity, community, repositories, metadata
          config_padding: 6%, 13%
          config_timezone: America/Los_Angeles
          
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          plugin_habits: yes
          plugin_habits_facts: yes
          
          plugin_introduction: yes
          
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: veritlog
          plugin_languages_limit: 20
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
          
          plugin_traffic: yes
          
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects-graphs, languages, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: insberr
